#!/usr/bin/env python3
"""Rebuild catalog.yml from front matter and run basic QA checks.

Draft production tooling only — not part of the runtime app, not shipped,
not a dependency of anything under apps/. Run from the working/ directory:

    python3 qa/build_catalog.py

Regenerates catalog.yml from every *.md file's front matter and prints a QA
report: duplicate IDs, missing required fields, non-false author_vetted,
broken `related` links, and unknown `source_ids`.
"""
import sys
import yaml
from pathlib import Path

WORKING = Path(__file__).resolve().parent.parent
FAMILY_DIRS = ["general", "tropes", "systems", "comparisons", "profiles"]

REQUIRED_FIELDS = [
    "id", "version", "title", "document_type", "family", "summary",
    "author_vetted", "detectability", "scopes", "applicability",
    "source_ids", "source_confidence",
]


def load_front_matter(path: Path):
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---"):
        return None, f"{path}: no front matter delimiter"
    parts = text.split("---", 2)
    if len(parts) < 3:
        return None, f"{path}: malformed front matter"
    try:
        fm = yaml.safe_load(parts[1])
    except yaml.YAMLError as e:
        return None, f"{path}: YAML parse error: {e}"
    return fm, None


def main():
    records = []
    errors = []
    ids_seen = {}

    for family_dir in FAMILY_DIRS:
        d = WORKING / family_dir
        if not d.exists():
            continue
        for path in sorted(d.glob("*.md")):
            fm, err = load_front_matter(path)
            if err:
                errors.append(err)
                continue
            rel_path = str(path.relative_to(WORKING))
            for field in REQUIRED_FIELDS:
                if field not in fm:
                    errors.append(f"{rel_path}: missing required field '{field}'")
            rid = fm.get("id")
            if rid:
                if rid in ids_seen:
                    errors.append(
                        f"{rel_path}: duplicate id '{rid}' (also in {ids_seen[rid]})"
                    )
                else:
                    ids_seen[rid] = rel_path
            if fm.get("author_vetted") is not False:
                errors.append(f"{rel_path}: author_vetted must be false, got {fm.get('author_vetted')!r}")
            records.append((rel_path, fm))

    # Load sources.yml for source_id validation
    sources_path = WORKING / "sources.yml"
    known_source_ids = set()
    if sources_path.exists():
        sdoc = yaml.safe_load(sources_path.read_text(encoding="utf-8")) or {}
        for s in sdoc.get("sources", []):
            known_source_ids.add(s["id"])
        known_source_ids.add("src.synthesis.craft-library-editorial")

    all_ids = set(ids_seen.keys())

    # Check related + source_ids references
    for rel_path, fm in records:
        for r in (fm.get("related") or []):
            if r not in all_ids:
                errors.append(f"{rel_path}: related id '{r}' not found among drafted records (pending)")
        for sid in (fm.get("source_ids") or []):
            if sid not in known_source_ids:
                errors.append(f"{rel_path}: source_id '{sid}' not found in sources.yml")

    # Build catalog
    catalog_records = []
    for rel_path, fm in sorted(records, key=lambda r: r[1].get("id", "")):
        catalog_records.append({
            "id": fm.get("id"),
            "title": fm.get("title"),
            "family": fm.get("family"),
            "document_type": fm.get("document_type"),
            "version": fm.get("version"),
            "detectability": fm.get("detectability"),
            "scopes": fm.get("scopes"),
            "applicability": fm.get("applicability"),
            "author_vetted": fm.get("author_vetted"),
            "path": rel_path,
        })

    catalog = {
        "generated_by": "qa/build_catalog.py (draft tooling, not runtime code)",
        "record_count": len(catalog_records),
        "records": catalog_records,
    }
    (WORKING / "catalog.yml").write_text(
        "# Working catalog — Writing Coach craft library (draft inventory)\n"
        "#\n"
        "# AUTO-GENERATED by qa/build_catalog.py from each record's front matter.\n"
        "# Do not hand-edit; re-run the script after adding or changing records.\n"
        "# Not the 4.17 runtime schema.\n\n"
        + yaml.safe_dump(catalog, sort_keys=False, allow_unicode=True, width=100),
        encoding="utf-8",
    )

    print(f"Wrote catalog.yml with {len(catalog_records)} records.")
    # Family/type breakdown
    from collections import Counter
    fam_counts = Counter(r["family"] for r in catalog_records)
    type_counts = Counter(r["document_type"] for r in catalog_records)
    det_counts = Counter(r["detectability"] for r in catalog_records)
    print("By family:", dict(fam_counts))
    print("By document_type:", dict(type_counts))
    print("By detectability:", dict(det_counts))

    if errors:
        print(f"\n{len(errors)} QA issue(s):")
        for e in errors:
            print(" -", e)
    else:
        print("\nNo QA issues found.")

    return 1 if any("missing required field" in e or "duplicate id" in e or "author_vetted" in e or "YAML parse" in e for e in errors) else 0


if __name__ == "__main__":
    sys.exit(main())
